name: qserver
description: A comprehensive, expressive, and type-safe Dart backend framework.
version: 0.0.17
homepage: https://github.com/MohammedAsaadAsaad/qserver
repository: https://github.com/MohammedAsaadAsaad/qserver
issue_tracker: https://github.com/MohammedAsaadAsaad/qserver/issues
topics:
  - server
  - http
  - websocket
  - backend
environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  qserver: qserver

dependencies:
  meta: ^1.19.0
  mime: ^2.0.0
  dart_jsonwebtoken: ^3.4.1
  # The Quds DB Ecosystem
  quds_db_interface: ^0.0.5
  quds_db_postgres: ^0.0.6
  quds_db_mysql: ^0.0.9
  redis: ^4.0.0
  http: ^1.2.0
  crypto: ^3.0.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.2
